baseURL = "http://example.org/"
languageCode = "en-us"
title = "Martin R. Wagner"
theme = "hallo"

[Author]
name = "Martin"

[params]
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/martin-r-wagner"
    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "google-scholar"
        title = "Google Scholar"
        url = "https://scholar.google.com/citations?user=ohWxMbcAAAAJ&hl=en"